/* 07 투자일지 — EPS 선행지표로 의사결정을 기록하고 사후 평가한다. */
(function () {
  'use strict';
  var API='/api/investment-journal', KEY='alphamap_investment_journal_v1', rows=[], editing=null, timer=null;
  var $=function(id){return document.getElementById(id);};
  var esc=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  var CSS=`
  #v-journal .jr-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(300px,.85fr);gap:14px;margin-bottom:18px}
  #v-journal .jr-card{background:var(--panel);border:1px solid var(--line);padding:16px 18px}
  #v-journal .jr-title{font-size:14px;font-weight:800;margin:0 0 12px;color:var(--txt)}
  #v-journal .jr-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}
  #v-journal label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700;color:var(--dim)}
  #v-journal label.wide{grid-column:1/-1}
  #v-journal input,#v-journal select,#v-journal textarea{width:100%;box-sizing:border-box;border:1px solid var(--line2);background:var(--panel2);color:var(--txt);padding:9px 10px;border-radius:3px;font:inherit;font-size:14px}
  #v-journal textarea{min-height:66px;resize:vertical;line-height:1.55}
  #v-journal input:focus,#v-journal select:focus,#v-journal textarea:focus{outline:2px solid color-mix(in srgb,var(--dawn) 28%,transparent);border-color:var(--dawn)}
  #v-journal .jr-actions{display:flex;align-items:center;gap:8px;margin-top:12px;flex-wrap:wrap}
  #v-journal .jr-btn{border:1px solid var(--line2);background:var(--panel2);color:var(--txt);padding:9px 13px;border-radius:3px;font:700 13px inherit;cursor:pointer}
  #v-journal .jr-btn.primary{background:var(--dawn);border-color:var(--dawn);color:var(--onacc)}
  #v-journal .jr-sync{margin-left:auto;font-size:12px;color:var(--faint)}
  #v-journal .jr-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-bottom:13px}
  #v-journal .jr-metric{border:1px solid var(--line);background:var(--panel2);padding:11px}
  #v-journal .jr-metric b{display:block;font-size:20px;color:var(--txt)}#v-journal .jr-metric span{font-size:11px;color:var(--faint)}
  #v-journal .jr-rule{font-size:13px;line-height:1.65;color:var(--dim);border-top:1px solid var(--line);padding-top:11px}
  #v-journal .jr-rule b{color:var(--txt)}
  #v-journal .jr-tools{display:flex;gap:8px;align-items:center;margin:0 0 10px;flex-wrap:wrap}
  #v-journal .jr-tools input{max-width:260px}.jr-count{font-size:12px;color:var(--faint)}
  #v-journal .jr-list{display:flex;flex-direction:column;border-top:1px solid var(--line)}
  #v-journal .jr-row{display:grid;grid-template-columns:92px 92px minmax(150px,1fr) minmax(170px,1.2fr) 92px 82px;gap:10px;align-items:start;padding:12px 4px;border-bottom:1px solid var(--line);font-size:13px}
  #v-journal .jr-head{font-size:11px;font-weight:800;color:var(--faint);padding-top:8px;padding-bottom:8px}
  #v-journal .jr-ticker{font-weight:800;color:var(--txt)}#v-journal .jr-sub{display:block;color:var(--faint);font-size:11px;margin-top:3px}
  #v-journal .jr-up{color:var(--st-dawn);font-weight:800}#v-journal .jr-down{color:var(--st-hot);font-weight:800}#v-journal .jr-flat{color:var(--dim);font-weight:800}
  #v-journal .jr-open{color:var(--st-mature);font-weight:800}#v-journal .jr-done{color:var(--st-dawn);font-weight:800}
  #v-journal .jr-empty{padding:42px 0;text-align:center;color:var(--faint);font-size:14px}
  @media(max-width:850px){#v-journal .jr-grid{grid-template-columns:1fr}#v-journal .jr-row{grid-template-columns:80px 80px 1fr}.jr-hide-sm{display:none}}
  @media(max-width:560px){#v-journal .jr-fields{grid-template-columns:1fr}#v-journal label.wide{grid-column:auto}#v-journal .jr-row{grid-template-columns:70px 72px 1fr;gap:7px}}
  `;
  var SECTION=`<div class="vhead"><div class="vkick">Investment Journal · 판단과 결과의 연결</div><h1 class="vtitle">수익률이 아니라 <em>EPS 선행지표</em>로 기록한다</h1><p class="vsub">매매 전 가설·촉매·EPS 트리거를 고정하고, 결과가 나온 뒤 분석·타이밍·비중을 따로 채점한다. 수익이 난 판단과 운이 좋았던 판단을 구분한다.</p></div>
  <div class="jr-grid"><form class="jr-card" id="jrForm"><h2 class="jr-title">판단 기록</h2><div class="jr-fields">
  <label>날짜<input id="jrDate" type="date" required></label><label>종목<input id="jrTicker" placeholder="예: MU" required></label>
  <label>행동<select id="jrAction"><option>매수</option><option>매도</option><option>유지</option><option>관찰</option></select></label><label>상태<select id="jrStatus"><option value="open">추적 중</option><option value="reviewed">사후평가 완료</option></select></label>
  <label>거래가격<input id="jrPrice" type="number" step="any"></label><label>비중 변화<input id="jrWeight" placeholder="예: 8% → 6%"></label>
  <label class="wide">핵심 투자 가설<textarea id="jrThesis" required placeholder="기업가치와 EPS가 왜 올라가는가"></textarea></label>
  <label class="wide">촉매와 시점<textarea id="jrCatalyst" placeholder="언제 무엇이 수주·매출·마진에 반영되는가"></textarea></label>
  <label>EPS 선행지표<input id="jrMetric" placeholder="예: FY+1 EPS 30일 리비전"></label><label>현재값·방향<input id="jrNow" placeholder="예: +6.2%, 상향 가속"></label>
  <label>매수·축소 트리거<input id="jrTrigger" placeholder="예: 리비전 +, 주가 30일 ≤ EPS"></label><label>판정<select id="jrDirection"><option value="up">강화</option><option value="flat">중립</option><option value="down">약화</option></select></label>
  <label>지표 기준일<input id="jrAsOf" type="date"></label><label>출처<input id="jrSource" placeholder="공시·실적자료·gamma.json"></label>
  <label class="wide">투자 논리 무효화 조건<textarea id="jrInvalid" placeholder="어떤 사실이 확인되면 가격과 무관하게 철회할 것인가"></textarea></label>
  <label class="wide">기대했던 결과<textarea id="jrExpected" placeholder="다음 실적까지 확인할 수치와 예상 경로"></textarea></label>
  <label>실현수익률 %<input id="jrReturn" type="number" step="0.1"></label><label>벤치마크 %<input id="jrBenchmark" type="number" step="0.1"></label>
  <label>가설 점수<select id="jrThesisScore"><option value="">미평가</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>타이밍 점수<select id="jrTimingScore"><option value="">미평가</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label>
  <label>비중 점수<select id="jrSizingScore"><option value="">미평가</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>실제 결과<input id="jrActual" placeholder="실적·주가 결과"></label>
  <label class="wide">배운 점·다음 규칙<textarea id="jrLesson" placeholder="분석, 가격, 비중 중 무엇이 맞거나 틀렸는가"></textarea></label>
  </div><div class="jr-actions"><button class="jr-btn primary" type="submit">기록 저장</button><button class="jr-btn" type="button" id="jrReset">새 기록</button><button class="jr-btn" type="button" id="jrDelete" hidden>삭제</button><span class="jr-sync" id="jrSync"></span></div></form>
  <aside class="jr-card"><h2 class="jr-title">학습 대시보드</h2><div class="jr-metrics" id="jrMetrics"></div><div class="jr-rule"><b>실행 순서</b><br>① EPS 선행지표와 기준일을 먼저 기록<br>② 가격이 EPS보다 앞섰는지 비교<br>③ 무효화 조건과 비중 상한을 결정<br>④ 결과 후 가설·타이밍·비중을 각각 채점<br><br><b>좋은 결과 ≠ 좋은 판단.</b> 벤치마크를 이겼더라도 가설이 틀렸다면 성공으로 분류하지 않는다.</div></aside></div>
  <div class="jr-card"><div class="jr-tools"><input id="jrSearch" placeholder="종목·가설·지표 검색"><select id="jrFilter"><option value="all">전체</option><option value="open">추적 중</option><option value="reviewed">사후평가 완료</option><option value="up">EPS 강화</option><option value="down">EPS 약화</option></select><span class="jr-count" id="jrCount"></span></div><div class="jr-list" id="jrList"></div></div>`;

  function getLocal(){try{var a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a:[];}catch(e){return [];}}
  function setLocal(){try{localStorage.setItem(KEY,JSON.stringify(rows));}catch(e){}}
  function sync(s){var e=$('jrSync');if(e)e.textContent=s==='saving'?'저장 중…':s==='saved'?'✓ 저장됨':s==='offline'?'⚠ 이 기기에만 저장됨':'';}
  function push(){clearTimeout(timer);sync('saving');timer=setTimeout(function(){fetch(API,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(rows)}).then(function(r){sync(r.ok?'saved':'offline');}).catch(function(){sync('offline');});},180);}
  function val(id){return ($(id)&&$(id).value||'').trim();} function num(id){var v=val(id);return v===''?null:Number(v);}
  function reset(){editing=null;$('jrForm').reset();$('jrDate').value=new Date().toISOString().slice(0,10);$('jrAsOf').value=$('jrDate').value;$('jrDelete').hidden=true;}
  function fill(r){editing=r.id;var m={jrDate:'date',jrTicker:'ticker',jrAction:'action',jrStatus:'status',jrPrice:'price',jrThesis:'thesis',jrCatalyst:'catalyst',jrMetric:'epsMetric',jrNow:'epsNow',jrTrigger:'epsTrigger',jrDirection:'epsDirection',jrAsOf:'epsAsOf',jrSource:'epsSource',jrInvalid:'invalid',jrExpected:'expected',jrReturn:'returnPct',jrBenchmark:'benchmarkPct',jrThesisScore:'thesisScore',jrTimingScore:'timingScore',jrSizingScore:'sizingScore',jrActual:'actual',jrLesson:'lesson'};Object.keys(m).forEach(function(id){$(id).value=r[m[id]]==null?'':r[m[id]];});$('jrWeight').value=(r.weightBefore==null?'':r.weightBefore+'%')+(r.weightAfter==null?'':' → '+r.weightAfter+'%');$('jrDelete').hidden=false;window.scrollTo({top:$('v-journal').offsetTop-20,behavior:'smooth'});}
  function metrics(){var done=rows.filter(function(r){return r.status==='reviewed';}), alpha=done.filter(function(r){return Number.isFinite(r.returnPct)&&Number.isFinite(r.benchmarkPct);}).map(function(r){return r.returnPct-r.benchmarkPct;}), avg=function(k){var a=done.map(function(r){return Number(r[k]);}).filter(Number.isFinite);return a.length?(a.reduce(function(x,y){return x+y;},0)/a.length).toFixed(1):'—';};$('jrMetrics').innerHTML='<div class="jr-metric"><b>'+rows.filter(function(r){return r.status!=='reviewed';}).length+'</b><span>추적 중</span></div><div class="jr-metric"><b>'+done.length+'</b><span>사후평가 완료</span></div><div class="jr-metric"><b>'+(alpha.length?(alpha.reduce(function(x,y){return x+y;},0)/alpha.length).toFixed(1)+'%p':'—')+'</b><span>평균 초과수익</span></div><div class="jr-metric"><b>'+avg('thesisScore')+' / 5</b><span>평균 가설 점수</span></div>';}
  function render(){metrics();var q=val('jrSearch').toLowerCase(),f=val('jrFilter')||'all';var a=rows.filter(function(r){var match=!q||[r.ticker,r.thesis,r.epsMetric,r.lesson].join(' ').toLowerCase().indexOf(q)>=0;return match&&(f==='all'||r.status===f||r.epsDirection===f);}).sort(function(a,b){return String(b.date).localeCompare(String(a.date));});$('jrCount').textContent=a.length+'건';var head='<div class="jr-row jr-head"><span>날짜</span><span>종목·행동</span><span>투자 가설</span><span class="jr-hide-sm">EPS 선행지표</span><span class="jr-hide-sm">초과수익</span><span>상태</span></div>';$('jrList').innerHTML=head+(a.length?a.map(function(r){var ex=Number.isFinite(r.returnPct)&&Number.isFinite(r.benchmarkPct)?(r.returnPct-r.benchmarkPct):null;return '<button type="button" class="jr-row" data-id="'+esc(r.id)+'" style="width:100%;text-align:left;background:transparent;border-left:0;border-right:0;border-top:0;color:inherit;cursor:pointer"><span>'+esc(r.date)+'</span><span class="jr-ticker">'+esc(r.ticker)+'<small class="jr-sub">'+esc(r.action)+'</small></span><span>'+esc(r.thesis||'—')+'</span><span class="jr-hide-sm"><b class="jr-'+esc(r.epsDirection||'flat')+'">'+esc(r.epsDirection==='up'?'강화':r.epsDirection==='down'?'약화':'중립')+'</b><small class="jr-sub">'+esc(r.epsMetric||'지표 미입력')+'</small></span><span class="jr-hide-sm">'+(ex==null?'—':(ex>0?'+':'')+ex.toFixed(1)+'%p')+'</span><span class="'+(r.status==='reviewed'?'jr-done':'jr-open')+'">'+(r.status==='reviewed'?'평가 완료':'추적 중')+'</span></button>';}).join(''):'<div class="jr-empty">아직 기록이 없습니다. 첫 판단의 EPS 트리거부터 남겨보세요.</div>');Array.prototype.forEach.call($('jrList').querySelectorAll('[data-id]'),function(b){b.onclick=function(){var r=rows.find(function(x){return x.id===b.dataset.id;});if(r)fill(r);};});}
  function save(e){e.preventDefault();var weight=val('jrWeight').match(/-?[\d.]+/g)||[];var now=new Date().toISOString();var old=rows.find(function(x){return x.id===editing;});var r={id:editing||('jr_'+Date.now()),date:val('jrDate'),ticker:val('jrTicker').toUpperCase(),action:val('jrAction'),status:val('jrStatus'),price:num('jrPrice'),weightBefore:weight[0]==null?null:Number(weight[0]),weightAfter:weight[1]==null?null:Number(weight[1]),thesis:val('jrThesis'),catalyst:val('jrCatalyst'),epsMetric:val('jrMetric'),epsNow:val('jrNow'),epsTrigger:val('jrTrigger'),epsDirection:val('jrDirection'),epsAsOf:val('jrAsOf'),epsSource:val('jrSource'),invalid:val('jrInvalid'),expected:val('jrExpected'),returnPct:num('jrReturn'),benchmarkPct:num('jrBenchmark'),thesisScore:num('jrThesisScore'),timingScore:num('jrTimingScore'),sizingScore:num('jrSizingScore'),actual:val('jrActual'),lesson:val('jrLesson'),createdAt:old&&old.createdAt||now,updatedAt:now};if(!r.date||!r.ticker||!r.thesis)return;if(old)rows[rows.indexOf(old)]=r;else rows.push(r);setLocal();push();render();reset();}
  function mount(){var nav=$('nav'),main=document.querySelector('main.wrap');if(!nav||!main)return;if(!$('journal-css')){var st=document.createElement('style');st.id='journal-css';st.textContent=CSS;document.head.appendChild(st);}var b=nav.querySelector('[data-v="journal"]');if(!b){b=document.createElement('button');b.className='tab';b.dataset.v='journal';b.innerHTML='<span class="n">07</span>투자일지';var brief=nav.querySelector('[data-v="brief"]'),memo=nav.querySelector('[data-v="memo"]');nav.insertBefore(b,brief||memo||null);}function renumber(){var n=1;Array.prototype.forEach.call(nav.querySelectorAll('.tab'),function(t){var e=t.querySelector('.n');if(!e)return;if(t.dataset.v==='world')e.textContent='00';else{e.textContent=(n<10?'0':'')+n;n++;}});}renumber();new MutationObserver(renumber).observe(nav,{childList:true});var sec=$('v-journal');if(!sec){sec=document.createElement('section');sec.className='view';sec.id='v-journal';sec.innerHTML=SECTION;var bv=$('v-brief'),mv=$('v-memo');main.insertBefore(sec,bv||mv||null);}nav.addEventListener('click',function(e){var t=e.target.closest&&e.target.closest('.tab');if(t&&t.dataset.v==='journal')render();});$('jrForm').onsubmit=save;$('jrReset').onclick=reset;$('jrDelete').onclick=function(){if(!editing||!confirm('이 투자일지를 삭제할까요?'))return;rows=rows.filter(function(x){return x.id!==editing;});setLocal();push();render();reset();};$('jrSearch').oninput=render;$('jrFilter').onchange=render;reset();rows=getLocal();render();fetch(API,{cache:'no-store'}).then(function(r){if(!r.ok)throw 0;return r.json();}).then(function(a){if(Array.isArray(a)){rows=a;setLocal();render();sync('saved');}}).catch(function(){sync('offline');});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
